### ISSUE TITLE
Twitter listed twice

### ISSUE THREAD

**Issue by lkiesow** [CTreffOS/ctreffos-webseite#17]
The English version now lists the Twitter account twice:

![Screenshot from 2023-01-28 21-07-45](https://user-images.githubusercontent.com/1008395/215288677-5ef20c50-4328-4369-9177-8a038c606950.png)

**Comment by petvoigt** [comment]
Argh, copy/paste error of my latest commit, thanks, fixed with commit 15cffe82eb6a0f4f62687bf8404c65c3a5edd18a.
