### ISSUE TITLE
 Don't use “here” links

### ISSUE THREAD

**Issue by lkiesow** [CTreffOS/ctreffos-webseite#18]
Using link descriptions like “Find it here” in the Matrix section is not great. Instead of copying it over, let me recommend the article [Don’t use “click here” …and other common hyperlink mistakes](https://heyoka.medium.com/dont-use-click-here-f32f445d1021) to learn about some reasoning behind this.

**Comment by petvoigt** [comment]
Thanks for this suggestion, fixed with commit 15cffe82eb6a0f4f62687bf8404c65c3a5edd18a.
