### ISSUE TITLE
ctreffos.de not available via HTTPS

### ISSUE THREAD

**Issue by lkiesow** [CTreffOS/ctreffos-webseite#5]
In times of Let's Encrypt, there is no reason to not make sites available via HTTPS:

```sh
% curl -If http://ctreffos.de
HTTP/1.1 302 Found
…
```
```
% curl -If https://ctreffos.de
curl: (35) error:14094458:SSL routines:ssl3_read_bytes:tlsv1 unrecognized name
```

**Comment by elanfer** [comment]
ctreffos.de is just an alias that is forwarded to https://chaostreff-osnbrueck.de. For this domain, https has always been configured since we changed the server. But  I also hold your point that we can put a cert on ctreffos.de for providing an initial page call via https as well. @petvoigt maybe you can add the domain in the LE certificate and adjust the listener?

**Comment by petvoigt** [comment]
On Fri, 01 Nov 2019 01:15:18 -0700
Eric Lanfer <notifications@github.com> wrote:

> ctreffos.de is just an alias that is forwarded to
> https://chaostreff-osnbrueck.de. For this domain, https has always
> been configured since we changed the server. But  I also hold your
> point that we can put a cert on ctreffos.de for providing an initial
> page call via https as well. @petvoigt maybe you can add the domain
> in the LE certificate and adjust the listener?
> 

Well, according to my understanding ctreffos.de is an outdated address
for our website. The domain ctreffos.de is owned by @elanfer and not
by Chaostreff Osnabrück e.V.. Therefore I propose to make either a
clear cut beetween ctreffos.de and chaostreff-osnabrueck.de or transfer
ctreffos.de to Chaostreff Osnabrueck e.V..

If we decide for the clear cut variant any DNS records pointing to the
main domain chaostreff-osnabrueck.de of our asscociation should be
deleted.

Btw.: What do you mean by "adjust the listener"?

**Comment by elanfer** [comment]
Since this was the first domain our website was associated with, we should transfer the ownership to the club and configure the server for providing https for this domain as well. I will discuss the details for transferring the domain with you and @jsaalfeld via xmpp.

**Comment by petvoigt** [comment]
@elanfer thanks for commenting this here. I am going to delay any work on the current issue until we have a final decision on the ownership and meaning of ctreffos.de

**Comment by lkiesow** [comment]
Sounds reasonable. In any case, I've changed the GitHub organizations website to `https://chaostreff-osnabrueck.de`.

**Comment by petvoigt** [comment]
lkiesow, thanks, right decision as our main official doamain is chaostreff-osnabrueck.de.

**Comment by razzeee** [comment]
So, can we close this?

**Comment by elanfer** [comment]
yep, solved, we're not using ctreffos.de anymore.
